import { useParams, Link } from 'react-router-dom';
import { motion } from 'motion/react';
import { ArrowLeft, Calendar, User, Tag, Share2, MessageCircle } from 'lucide-react';
import { blogPosts } from './Blog';
import { formatDate } from '../lib/utils';
import Markdown from 'react-markdown';

export default function BlogPost() {
  const { id } = useParams();
  const post = blogPosts.find(p => p.id === id) || blogPosts[0];

  const mockContent = `
## The Philosophy of Quality

In an era where content is increasingly generated by algorithms, the value of the human voice has never been higher. At Goldleaf, we believe that a truly great book isn't just about information—it's about resonance.

### Why Nuance Matters

When we sit down with an author, we don't just listen to the facts of their life. We listen for the pauses. We listen for the specific choice of words that signal their unique worldview. This "voice matching" is what separates a ghostwriter from a transcriber.

*   *Authenticity:* The reader must feel the pulse of the author on every page.
*   *Structure:* A story is a journey. We architect the path.
*   *Legacy:* We aren't writing for next week. We're writing for next century.

### The Path Forward

Whether you are just starting your manuscript or looking for an elite editor to polish a completed draft, the goal remains the same: excellence without compromise.
  `;

  return (
    <div className="pt-32 pb-24 bg-paper min-h-screen">
      <div className="container mx-auto px-6 max-w-4xl">
        <Link 
          to="/blog" 
          className="inline-flex items-center text-[10px] uppercase tracking-widest font-bold text-ink/40 hover:text-gold mb-12 transition-colors"
        >
          <ArrowLeft className="mr-2 w-4 h-4" />
          Back to all articles
        </Link>
        
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="flex items-center space-x-6 mb-8">
            <span className="bg-gold text-white text-[10px] uppercase font-bold tracking-widest px-4 py-1 rounded-full">
              {post.category}
            </span>
            <div className="flex items-center text-ink/40 text-[10px] uppercase font-bold tracking-widest">
              <Calendar className="w-3 h-3 mr-2" />
              {formatDate(post.date)}
            </div>
            <div className="flex items-center text-ink/40 text-[10px] uppercase font-bold tracking-widest">
              <User className="w-3 h-3 mr-2" />
              {post.author}
            </div>
          </div>

          <h1 className="text-4xl md:text-6xl font-serif font-bold tracking-tight text-ink mb-12 leading-tight">
            {post.title}
          </h1>

          <div className="aspect-[21/9] rounded-[40px] overflow-hidden border border-black/5 mb-16 shadow-2xl">
            <img 
              src={post.image} 
              alt={post.title} 
              className="w-full h-full object-cover grayscale"
              referrerPolicy="no-referrer"
            />
          </div>

          <div className="prose prose-lg dark:prose-invert max-w-none prose-serif font-serif italic text-ink/80 leading-relaxed markdown-body">
            <Markdown>{mockContent}</Markdown>
          </div>

          <div className="mt-20 pt-10 border-t border-black/5 flex flex-col md:flex-row justify-between items-center gap-8">
            <div className="flex items-center space-x-4">
              <img 
                src="https://picsum.photos/seed/author/100/100" 
                alt={post.author} 
                className="w-14 h-14 rounded-full grayscale border border-black/10"
                referrerPolicy="no-referrer"
              />
              <div>
                <h4 className="text-sm font-bold uppercase tracking-widest">{post.author}</h4>
                <p className="text-xs text-ink/40 font-serif italic">Lead Narrative Architect at Goldleaf</p>
              </div>
            </div>
            <div className="flex space-x-4">
              <button className="flex items-center space-x-2 bg-paper border border-black/5 px-6 py-3 rounded-xl text-[10px] uppercase font-bold tracking-widest hover:border-gold transition-colors">
                <Share2 className="w-4 h-4" />
                <span>Share</span>
              </button>
              <Link 
                to="/contact"
                className="flex items-center space-x-2 bg-ink text-white px-6 py-3 rounded-xl text-[10px] uppercase font-bold tracking-widest hover:bg-gold transition-colors"
              >
                <MessageCircle className="w-4 h-4" />
                <span>Consult</span>
              </Link>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
